### ISSUE TITLE
/g home error

### ISSUE THREAD

**Issue by DegenApeDev** [NeuroBinds/Simple-Guilds-Management#11]
Seems to teleport you to a flat world and kills you when you issue /g home 

any idea what to fix??

**Comment by DegenApeDev** [comment]
Also this happens when Factions is in another world..  When you do /g home from the other world it teleports you to the location., Perhaps this needs to be fixed to call the world in which the faction home is in..  

I think this is a multiworld issue..

**Comment by Adam1609** [comment]
No, that happened on first version on factionspro, just forget that please :)

**Comment by NeuroBinds** [comment]
This project is not so active , if we or i had time to check and update it we willl do it
but @HyGlobalHD and me had examination in 1 week so we not that very active for now..
maybe after the examination :-:

**Comment by NeuroBinds** [comment]
Hello Hello xD You Can Try #14 Maybe Can Help With This Error :P
