### ISSUE TITLE
Not reading from guilds options config

### ISSUE THREAD

**Issue by kabluinc** [NeuroBinds/Simple-Guilds-Management#15]
Hi, I have tried changing some options like plot cost and plot claim worlds but after server restart it still doesn't register the changes. it is still using the default options. when I type /g claim it says u must be in a  faction world and when I do /g create it needs $3000. although iv changed these in the config already

**Comment by HyGlobalHD** [comment]
for the config,
worldclaim :
- worldname

and about the plotcost which version you use is it master or #14 ?

**Comment by HyGlobalHD** [comment]
it seems there arent any conflict about create cost..
wait are you ask about create cost or claim cost because you ask about claim and claim cost but you ask /g create

**Comment by HyGlobalHD** [comment]
If it about /g claim then there nothing wrong because the cost of the claim also determine by the plotsize

**Comment by HyGlobalHD** [comment]
Example of the config this for branch #14  
---
MaxGuildNameLength: 15
MaxPlayersPerguild: 30
OnlyGuildsMasterAndSecondInCommandsCanInvite: true
0: '###Plots###'
SecondInCommandsCanClaim: false
PlotSize: 30
PlayersNeededInGuildToClaimAPlot: 1
ClaimWorlds: 
- interfantasy
1: '###Guilds Point###'
PointNeededToClaimAPlot: 1000
PointNeededToSetOrUpdateAHome: 250
PointGainedPerPlayerInGuild: 50
PointGainedPerKillingAnEnemy: 10
PointReducedPerDeathByAnEnemy: 10
PointGainedPerAlliance: 100
AllianceLimitPerGuild: 5
TheDefaultPointEveryGuildStartsWith: 0
TheDefaultGuildsMoneyEveryGuildStartsWith: 0
TheDefaultWarPointsEveryGuildStartsWith: 0
2: '###Economys###'
CreateCost: 3000
ClaimCost: 100000
OverClaimCost: 25000
AllianceCost: 5000
AlliancePrice: 5000
SetHomeCost: 150
3: '###GuildsMoneys###'
GuildsMoneyGainPerKill: 10
GuildsMoneyLostPerDeath: 10
...

**Comment by HyGlobalHD** [comment]
Dont use #14 yet because  it unstable

**Comment by HyGlobalHD** [comment]
master branch doesn't have any conflict with this issues if you have error please post it down.
Thx. For Using This Plugin

**Comment by NeuroBinds** [comment]
i fix some major error at #14 , you can try it
