### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by FaanMaario** [NeuroBinds/Simple-Guilds-Management#3]
Hi,

Fist of all, I would like to say thanks to your plugin; **it's amazing and all I wanted !**
But there's some issues;
## **1) with the /guilds help command;**

When I type `/guilds help 1, 2, 3, 4, 5` it works fine, but the 6th page is not showed :/
## **2) claim command;**

I don't know if it's an issue or not, but there's no claim command.

---

So that's it, thanks for answering and for helping me :)

**Comment by HyGlobalHD** [comment]
omg xD I'm so idiot :P .
Thanks For Notice this .
Actually there no the six help commands.
and actually there are no commands to claim.
I will fix the help commands..

**Comment by FaanMaario** [comment]
Thank you, and no problem; The error is human :)

**Comment by HyGlobalHD** [comment]
Okey, Fixed the human error xD
thanks for using this plugin.
