### ISSUE TITLE
Suggestions 

### ISSUE THREAD

**Issue by daniktheboss** [NeuroBinds/Simple-Guilds-Management#4]
1. Claim command
2. Guild cost.. for example in config set how much each block costs and when u do claim... it calculates how much everything in the claim costs... (will take years XD)
3. Top guilds
4. In config folder show guilds and everyone in the guild and info about guild.
5. Make a command /g not /guilds
   Hope you take (some) suggestions lol thanks

**Comment by HyGlobalHD** [comment]
Claim Features Done
Claim Cost Done
Top Guilds Already Implement 
Config Folders (seems Unreasonable because already use db)
Add /g commands

**Comment by HyGlobalHD** [comment]
Thanks For Suggestion

**Comment by daniktheboss** [comment]
Thanks!

**Comment by daniktheboss** [comment]
Claim cost isn't implemented... there's no command for it

**Comment by daniktheboss** [comment]
Also... is there admin bypass mode?

**Comment by HyGlobalHD** [comment]
yeah actually if you do /guilds help 5 or 6
iy will shows available commands but it for OP , I Will add permission after i finish with something

and the claim cost i will implement later on..

**Comment by daniktheboss** [comment]
OK thanks Very much!
