### ISSUE TITLE
Guild Updates

### ISSUE THREAD

**Issue by juiceluqi** [NeuroBinds/Simple-Guilds-Management#7]
I will add is in effect /g info plz, and also boat War Points :D

**Comment by HyGlobalHD** [comment]
Can You Tell Me Specific What You Want?

**Comment by juiceluqi** [comment]
boat effects on /g info to show their points w effects of war and also add when /g war be teleported to an arena or specific cords

**Comment by HyGlobalHD** [comment]
You means is put [is in effects] in /g info
also about /g war it will be hard cause if the player from a specific faction is inactive then how they gonna be tp?

**Comment by EnderKenji** [comment]
Please focus on CPEFactions. :(

**Comment by HyGlobalHD** [comment]
@EnderKenji I want To, But GitLab load one page about 3 mins :-:

**Comment by juiceluqi** [comment]
Dm Twitter -> @HeyGalatico
